name: Maven CI/CD

on:
 push:
    branches: [ master ]
 pull_request:
    branches: [ master ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout main branch
      uses: actions/checkout@v2
    - name: 2. Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
        
    - name: 3. Set up cache for Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2      

    - name: 4. Build project with Maven
      run: mvn -B package --file pom.xml
